/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSendOfferRouteImport } from './routes/_app.send-offer'
import { Route as AppOffersRouteImport } from './routes/_app.offers'
import { Route as AppIntakeCampaignRouteImport } from './routes/_app.intake-campaign'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppImportLeadsRouteImport } from './routes/_app.import-leads'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as ApiIntrospectTamarRoutingRouteImport } from './routes/api/introspect/tamar-routing'
import { Route as ApiIntrospectTamarConfigRouteImport } from './routes/api/introspect/tamar-config'
import { Route as ApiIntrospectSystemOverviewRouteImport } from './routes/api/introspect/system-overview'
import { Route as ApiIntrospectSchemaSummaryRouteImport } from './routes/api/introspect/schema-summary'
import { Route as ApiIntrospectIntegrationsStatusRouteImport } from './routes/api/introspect/integrations-status'
import { Route as ApiIntrospectFrontendMapRouteImport } from './routes/api/introspect/frontend-map'
import { Route as ApiIntrospectCrmSummaryRouteImport } from './routes/api/introspect/crm-summary'
import { Route as ApiIntrospectCampaignsSummaryRouteImport } from './routes/api/introspect/campaigns-summary'
import { Route as ApiIntrospectBackendMapRouteImport } from './routes/api/introspect/backend-map'
import { Route as ApiIntrospectAgentsSummaryRouteImport } from './routes/api/introspect/agents-summary'
import { Route as ApiDebugTamarConfigRouteImport } from './routes/api/debug/tamar-config'
import { Route as ApiDebugSystemSummaryRouteImport } from './routes/api/debug/system-summary'
import { Route as ApiDebugSchemaSummaryRouteImport } from './routes/api/debug/schema-summary'
import { Route as ApiDebugRecentEventsRouteImport } from './routes/api/debug/recent-events'
import { Route as ApiDebugIntegrationsStatusRouteImport } from './routes/api/debug/integrations-status'
import { Route as ApiDebugFrontendMapRouteImport } from './routes/api/debug/frontend-map'
import { Route as ApiDebugAgentsSummaryRouteImport } from './routes/api/debug/agents-summary'
import { Route as AppSettingsApiRouteImport } from './routes/_app.settings.api'
import { Route as AppOffersIdRouteImport } from './routes/_app.offers.$id'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as ApiPublicWebhookTamarStatusRouteImport } from './routes/api/public/webhook/tamar-status'
import { Route as ApiPublicWebhookTamarRouteImport } from './routes/api/public/webhook/tamar'
import { Route as ApiPublicIntelligenceExtractRouteImport } from './routes/api/public/intelligence/extract'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSendOfferRoute = AppSendOfferRouteImport.update({
  id: '/send-offer',
  path: '/send-offer',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeCampaignRoute = AppIntakeCampaignRouteImport.update({
  id: '/intake-campaign',
  path: '/intake-campaign',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppImportLeadsRoute = AppImportLeadsRouteImport.update({
  id: '/import-leads',
  path: '/import-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const ApiIntrospectTamarRoutingRoute =
  ApiIntrospectTamarRoutingRouteImport.update({
    id: '/api/introspect/tamar-routing',
    path: '/api/introspect/tamar-routing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectTamarConfigRoute =
  ApiIntrospectTamarConfigRouteImport.update({
    id: '/api/introspect/tamar-config',
    path: '/api/introspect/tamar-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectSystemOverviewRoute =
  ApiIntrospectSystemOverviewRouteImport.update({
    id: '/api/introspect/system-overview',
    path: '/api/introspect/system-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectSchemaSummaryRoute =
  ApiIntrospectSchemaSummaryRouteImport.update({
    id: '/api/introspect/schema-summary',
    path: '/api/introspect/schema-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectIntegrationsStatusRoute =
  ApiIntrospectIntegrationsStatusRouteImport.update({
    id: '/api/introspect/integrations-status',
    path: '/api/introspect/integrations-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectFrontendMapRoute =
  ApiIntrospectFrontendMapRouteImport.update({
    id: '/api/introspect/frontend-map',
    path: '/api/introspect/frontend-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectCrmSummaryRoute = ApiIntrospectCrmSummaryRouteImport.update({
  id: '/api/introspect/crm-summary',
  path: '/api/introspect/crm-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntrospectCampaignsSummaryRoute =
  ApiIntrospectCampaignsSummaryRouteImport.update({
    id: '/api/introspect/campaigns-summary',
    path: '/api/introspect/campaigns-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectBackendMapRoute = ApiIntrospectBackendMapRouteImport.update({
  id: '/api/introspect/backend-map',
  path: '/api/introspect/backend-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntrospectAgentsSummaryRoute =
  ApiIntrospectAgentsSummaryRouteImport.update({
    id: '/api/introspect/agents-summary',
    path: '/api/introspect/agents-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugTamarConfigRoute = ApiDebugTamarConfigRouteImport.update({
  id: '/api/debug/tamar-config',
  path: '/api/debug/tamar-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSystemSummaryRoute = ApiDebugSystemSummaryRouteImport.update({
  id: '/api/debug/system-summary',
  path: '/api/debug/system-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSchemaSummaryRoute = ApiDebugSchemaSummaryRouteImport.update({
  id: '/api/debug/schema-summary',
  path: '/api/debug/schema-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRecentEventsRoute = ApiDebugRecentEventsRouteImport.update({
  id: '/api/debug/recent-events',
  path: '/api/debug/recent-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugIntegrationsStatusRoute =
  ApiDebugIntegrationsStatusRouteImport.update({
    id: '/api/debug/integrations-status',
    path: '/api/debug/integrations-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugFrontendMapRoute = ApiDebugFrontendMapRouteImport.update({
  id: '/api/debug/frontend-map',
  path: '/api/debug/frontend-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugAgentsSummaryRoute = ApiDebugAgentsSummaryRouteImport.update({
  id: '/api/debug/agents-summary',
  path: '/api/debug/agents-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsApiRoute = AppSettingsApiRouteImport.update({
  id: '/settings/api',
  path: '/settings/api',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIdRoute = AppOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOffersRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const ApiPublicWebhookTamarStatusRoute =
  ApiPublicWebhookTamarStatusRouteImport.update({
    id: '/api/public/webhook/tamar-status',
    path: '/api/public/webhook/tamar-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookTamarRoute = ApiPublicWebhookTamarRouteImport.update({
  id: '/api/public/webhook/tamar',
  path: '/api/public/webhook/tamar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntelligenceExtractRoute =
  ApiPublicIntelligenceExtractRouteImport.update({
    id: '/api/public/intelligence/extract',
    path: '/api/public/intelligence/extract',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/import-leads': typeof AppImportLeadsRoute
  '/inbox': typeof AppInboxRoute
  '/intake-campaign': typeof AppIntakeCampaignRoute
  '/offers': typeof AppOffersRouteWithChildren
  '/send-offer': typeof AppSendOfferRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/import-leads': typeof AppImportLeadsRoute
  '/inbox': typeof AppInboxRoute
  '/intake-campaign': typeof AppIntakeCampaignRoute
  '/offers': typeof AppOffersRouteWithChildren
  '/send-offer': typeof AppSendOfferRoute
  '/': typeof AppIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/import-leads': typeof AppImportLeadsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/intake-campaign': typeof AppIntakeCampaignRoute
  '/_app/offers': typeof AppOffersRouteWithChildren
  '/_app/send-offer': typeof AppSendOfferRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/offers/$id': typeof AppOffersIdRoute
  '/_app/settings/api': typeof AppSettingsApiRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/campaigns'
    | '/contacts'
    | '/import-leads'
    | '/inbox'
    | '/intake-campaign'
    | '/offers'
    | '/send-offer'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/contacts/$id'
    | '/offers/$id'
    | '/settings/api'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/frontend-map'
    | '/api/introspect/integrations-status'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/public/intelligence/extract'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/campaigns'
    | '/contacts'
    | '/import-leads'
    | '/inbox'
    | '/intake-campaign'
    | '/offers'
    | '/send-offer'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/contacts/$id'
    | '/offers/$id'
    | '/settings/api'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/frontend-map'
    | '/api/introspect/integrations-status'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/public/intelligence/extract'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/campaigns'
    | '/_app/contacts'
    | '/_app/import-leads'
    | '/_app/inbox'
    | '/_app/intake-campaign'
    | '/_app/offers'
    | '/_app/send-offer'
    | '/_app/'
    | '/_app/campaigns/$id'
    | '/_app/campaigns/new'
    | '/_app/contacts/$id'
    | '/_app/offers/$id'
    | '/_app/settings/api'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/frontend-map'
    | '/api/introspect/integrations-status'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/public/intelligence/extract'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDebugAgentsSummaryRoute: typeof ApiDebugAgentsSummaryRoute
  ApiDebugFrontendMapRoute: typeof ApiDebugFrontendMapRoute
  ApiDebugIntegrationsStatusRoute: typeof ApiDebugIntegrationsStatusRoute
  ApiDebugRecentEventsRoute: typeof ApiDebugRecentEventsRoute
  ApiDebugSchemaSummaryRoute: typeof ApiDebugSchemaSummaryRoute
  ApiDebugSystemSummaryRoute: typeof ApiDebugSystemSummaryRoute
  ApiDebugTamarConfigRoute: typeof ApiDebugTamarConfigRoute
  ApiIntrospectAgentsSummaryRoute: typeof ApiIntrospectAgentsSummaryRoute
  ApiIntrospectBackendMapRoute: typeof ApiIntrospectBackendMapRoute
  ApiIntrospectCampaignsSummaryRoute: typeof ApiIntrospectCampaignsSummaryRoute
  ApiIntrospectCrmSummaryRoute: typeof ApiIntrospectCrmSummaryRoute
  ApiIntrospectFrontendMapRoute: typeof ApiIntrospectFrontendMapRoute
  ApiIntrospectIntegrationsStatusRoute: typeof ApiIntrospectIntegrationsStatusRoute
  ApiIntrospectSchemaSummaryRoute: typeof ApiIntrospectSchemaSummaryRoute
  ApiIntrospectSystemOverviewRoute: typeof ApiIntrospectSystemOverviewRoute
  ApiIntrospectTamarConfigRoute: typeof ApiIntrospectTamarConfigRoute
  ApiIntrospectTamarRoutingRoute: typeof ApiIntrospectTamarRoutingRoute
  ApiPublicIntelligenceExtractRoute: typeof ApiPublicIntelligenceExtractRoute
  ApiPublicWebhookTamarRoute: typeof ApiPublicWebhookTamarRoute
  ApiPublicWebhookTamarStatusRoute: typeof ApiPublicWebhookTamarStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send-offer': {
      id: '/_app/send-offer'
      path: '/send-offer'
      fullPath: '/send-offer'
      preLoaderRoute: typeof AppSendOfferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake-campaign': {
      id: '/_app/intake-campaign'
      path: '/intake-campaign'
      fullPath: '/intake-campaign'
      preLoaderRoute: typeof AppIntakeCampaignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-leads': {
      id: '/_app/import-leads'
      path: '/import-leads'
      fullPath: '/import-leads'
      preLoaderRoute: typeof AppImportLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/introspect/tamar-routing': {
      id: '/api/introspect/tamar-routing'
      path: '/api/introspect/tamar-routing'
      fullPath: '/api/introspect/tamar-routing'
      preLoaderRoute: typeof ApiIntrospectTamarRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/tamar-config': {
      id: '/api/introspect/tamar-config'
      path: '/api/introspect/tamar-config'
      fullPath: '/api/introspect/tamar-config'
      preLoaderRoute: typeof ApiIntrospectTamarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/system-overview': {
      id: '/api/introspect/system-overview'
      path: '/api/introspect/system-overview'
      fullPath: '/api/introspect/system-overview'
      preLoaderRoute: typeof ApiIntrospectSystemOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/schema-summary': {
      id: '/api/introspect/schema-summary'
      path: '/api/introspect/schema-summary'
      fullPath: '/api/introspect/schema-summary'
      preLoaderRoute: typeof ApiIntrospectSchemaSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/integrations-status': {
      id: '/api/introspect/integrations-status'
      path: '/api/introspect/integrations-status'
      fullPath: '/api/introspect/integrations-status'
      preLoaderRoute: typeof ApiIntrospectIntegrationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/frontend-map': {
      id: '/api/introspect/frontend-map'
      path: '/api/introspect/frontend-map'
      fullPath: '/api/introspect/frontend-map'
      preLoaderRoute: typeof ApiIntrospectFrontendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/crm-summary': {
      id: '/api/introspect/crm-summary'
      path: '/api/introspect/crm-summary'
      fullPath: '/api/introspect/crm-summary'
      preLoaderRoute: typeof ApiIntrospectCrmSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/campaigns-summary': {
      id: '/api/introspect/campaigns-summary'
      path: '/api/introspect/campaigns-summary'
      fullPath: '/api/introspect/campaigns-summary'
      preLoaderRoute: typeof ApiIntrospectCampaignsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/backend-map': {
      id: '/api/introspect/backend-map'
      path: '/api/introspect/backend-map'
      fullPath: '/api/introspect/backend-map'
      preLoaderRoute: typeof ApiIntrospectBackendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/agents-summary': {
      id: '/api/introspect/agents-summary'
      path: '/api/introspect/agents-summary'
      fullPath: '/api/introspect/agents-summary'
      preLoaderRoute: typeof ApiIntrospectAgentsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/tamar-config': {
      id: '/api/debug/tamar-config'
      path: '/api/debug/tamar-config'
      fullPath: '/api/debug/tamar-config'
      preLoaderRoute: typeof ApiDebugTamarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/system-summary': {
      id: '/api/debug/system-summary'
      path: '/api/debug/system-summary'
      fullPath: '/api/debug/system-summary'
      preLoaderRoute: typeof ApiDebugSystemSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/schema-summary': {
      id: '/api/debug/schema-summary'
      path: '/api/debug/schema-summary'
      fullPath: '/api/debug/schema-summary'
      preLoaderRoute: typeof ApiDebugSchemaSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/recent-events': {
      id: '/api/debug/recent-events'
      path: '/api/debug/recent-events'
      fullPath: '/api/debug/recent-events'
      preLoaderRoute: typeof ApiDebugRecentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/integrations-status': {
      id: '/api/debug/integrations-status'
      path: '/api/debug/integrations-status'
      fullPath: '/api/debug/integrations-status'
      preLoaderRoute: typeof ApiDebugIntegrationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/frontend-map': {
      id: '/api/debug/frontend-map'
      path: '/api/debug/frontend-map'
      fullPath: '/api/debug/frontend-map'
      preLoaderRoute: typeof ApiDebugFrontendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/agents-summary': {
      id: '/api/debug/agents-summary'
      path: '/api/debug/agents-summary'
      fullPath: '/api/debug/agents-summary'
      preLoaderRoute: typeof ApiDebugAgentsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/api': {
      id: '/_app/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AppSettingsApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers/$id': {
      id: '/_app/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AppOffersIdRouteImport
      parentRoute: typeof AppOffersRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/api/public/webhook/tamar-status': {
      id: '/api/public/webhook/tamar-status'
      path: '/api/public/webhook/tamar-status'
      fullPath: '/api/public/webhook/tamar-status'
      preLoaderRoute: typeof ApiPublicWebhookTamarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/tamar': {
      id: '/api/public/webhook/tamar'
      path: '/api/public/webhook/tamar'
      fullPath: '/api/public/webhook/tamar'
      preLoaderRoute: typeof ApiPublicWebhookTamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intelligence/extract': {
      id: '/api/public/intelligence/extract'
      path: '/api/public/intelligence/extract'
      fullPath: '/api/public/intelligence/extract'
      preLoaderRoute: typeof ApiPublicIntelligenceExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppOffersRouteChildren {
  AppOffersIdRoute: typeof AppOffersIdRoute
}

const AppOffersRouteChildren: AppOffersRouteChildren = {
  AppOffersIdRoute: AppOffersIdRoute,
}

const AppOffersRouteWithChildren = AppOffersRoute._addFileChildren(
  AppOffersRouteChildren,
)

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppImportLeadsRoute: typeof AppImportLeadsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntakeCampaignRoute: typeof AppIntakeCampaignRoute
  AppOffersRoute: typeof AppOffersRouteWithChildren
  AppSendOfferRoute: typeof AppSendOfferRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsApiRoute: typeof AppSettingsApiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppImportLeadsRoute: AppImportLeadsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntakeCampaignRoute: AppIntakeCampaignRoute,
  AppOffersRoute: AppOffersRouteWithChildren,
  AppSendOfferRoute: AppSendOfferRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsApiRoute: AppSettingsApiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDebugAgentsSummaryRoute: ApiDebugAgentsSummaryRoute,
  ApiDebugFrontendMapRoute: ApiDebugFrontendMapRoute,
  ApiDebugIntegrationsStatusRoute: ApiDebugIntegrationsStatusRoute,
  ApiDebugRecentEventsRoute: ApiDebugRecentEventsRoute,
  ApiDebugSchemaSummaryRoute: ApiDebugSchemaSummaryRoute,
  ApiDebugSystemSummaryRoute: ApiDebugSystemSummaryRoute,
  ApiDebugTamarConfigRoute: ApiDebugTamarConfigRoute,
  ApiIntrospectAgentsSummaryRoute: ApiIntrospectAgentsSummaryRoute,
  ApiIntrospectBackendMapRoute: ApiIntrospectBackendMapRoute,
  ApiIntrospectCampaignsSummaryRoute: ApiIntrospectCampaignsSummaryRoute,
  ApiIntrospectCrmSummaryRoute: ApiIntrospectCrmSummaryRoute,
  ApiIntrospectFrontendMapRoute: ApiIntrospectFrontendMapRoute,
  ApiIntrospectIntegrationsStatusRoute: ApiIntrospectIntegrationsStatusRoute,
  ApiIntrospectSchemaSummaryRoute: ApiIntrospectSchemaSummaryRoute,
  ApiIntrospectSystemOverviewRoute: ApiIntrospectSystemOverviewRoute,
  ApiIntrospectTamarConfigRoute: ApiIntrospectTamarConfigRoute,
  ApiIntrospectTamarRoutingRoute: ApiIntrospectTamarRoutingRoute,
  ApiPublicIntelligenceExtractRoute: ApiPublicIntelligenceExtractRoute,
  ApiPublicWebhookTamarRoute: ApiPublicWebhookTamarRoute,
  ApiPublicWebhookTamarStatusRoute: ApiPublicWebhookTamarStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
