/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSendOfferRouteImport } from './routes/_app.send-offer'
import { Route as AppRuntimeTraceRouteImport } from './routes/_app.runtime-trace'
import { Route as AppOffersRouteImport } from './routes/_app.offers'
import { Route as AppManagerAlertsRouteImport } from './routes/_app.manager-alerts'
import { Route as AppIntakeCampaignRouteImport } from './routes/_app.intake-campaign'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppImportLeadsRouteImport } from './routes/_app.import-leads'
import { Route as AppHandoffRouteImport } from './routes/_app.handoff'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as ApiIntrospectUiGapsRouteImport } from './routes/api/introspect/ui-gaps'
import { Route as ApiIntrospectTamarRoutingRouteImport } from './routes/api/introspect/tamar-routing'
import { Route as ApiIntrospectTamarConfigRouteImport } from './routes/api/introspect/tamar-config'
import { Route as ApiIntrospectSystemOverviewRouteImport } from './routes/api/introspect/system-overview'
import { Route as ApiIntrospectSchemaSummaryRouteImport } from './routes/api/introspect/schema-summary'
import { Route as ApiIntrospectRecentEventsRouteImport } from './routes/api/introspect/recent-events'
import { Route as ApiIntrospectIntegrationsStatusRouteImport } from './routes/api/introspect/integrations-status'
import { Route as ApiIntrospectHealthReportRouteImport } from './routes/api/introspect/health-report'
import { Route as ApiIntrospectFrontendMapRouteImport } from './routes/api/introspect/frontend-map'
import { Route as ApiIntrospectFeatureFlagsRouteImport } from './routes/api/introspect/feature-flags'
import { Route as ApiIntrospectDeploymentSummaryRouteImport } from './routes/api/introspect/deployment-summary'
import { Route as ApiIntrospectCrmSummaryRouteImport } from './routes/api/introspect/crm-summary'
import { Route as ApiIntrospectCampaignsSummaryRouteImport } from './routes/api/introspect/campaigns-summary'
import { Route as ApiIntrospectBackendMapRouteImport } from './routes/api/introspect/backend-map'
import { Route as ApiIntrospectAgentsSummaryRouteImport } from './routes/api/introspect/agents-summary'
import { Route as ApiDebugTamarConfigRouteImport } from './routes/api/debug/tamar-config'
import { Route as ApiDebugSystemSummaryRouteImport } from './routes/api/debug/system-summary'
import { Route as ApiDebugSchemaSummaryRouteImport } from './routes/api/debug/schema-summary'
import { Route as ApiDebugRecentEventsRouteImport } from './routes/api/debug/recent-events'
import { Route as ApiDebugIntegrationsStatusRouteImport } from './routes/api/debug/integrations-status'
import { Route as ApiDebugFrontendMapRouteImport } from './routes/api/debug/frontend-map'
import { Route as ApiDebugAgentsSummaryRouteImport } from './routes/api/debug/agents-summary'
import { Route as AppSettingsTamarBlocksRouteImport } from './routes/_app.settings.tamar-blocks'
import { Route as AppSettingsTamarRouteImport } from './routes/_app.settings.tamar'
import { Route as AppSettingsApiRouteImport } from './routes/_app.settings.api'
import { Route as AppOffersIdRouteImport } from './routes/_app.offers.$id'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as ApiPublicWebhookTamarStatusRouteImport } from './routes/api/public/webhook/tamar-status'
import { Route as ApiPublicWebhookTamarRouteImport } from './routes/api/public/webhook/tamar'
import { Route as ApiPublicRuntimeWritebackRouteImport } from './routes/api/public/runtime/writeback'
import { Route as ApiPublicRuntimeTamarWritebackRouteImport } from './routes/api/public/runtime/tamar-writeback'
import { Route as ApiPublicRuntimeTamarTurnRouteImport } from './routes/api/public/runtime/tamar-turn'
import { Route as ApiPublicRuntimeTamarPackRouteImport } from './routes/api/public/runtime/tamar-pack'
import { Route as ApiPublicRuntimeLeadContextRouteImport } from './routes/api/public/runtime/lead-context'
import { Route as ApiPublicRuntimeHandoffRouteImport } from './routes/api/public/runtime/handoff'
import { Route as ApiPublicIntelligenceExtractRouteImport } from './routes/api/public/intelligence/extract'
import { Route as ApiPublicCronRetryHandoffsRouteImport } from './routes/api/public/cron/retry-handoffs'
import { Route as ApiPublicAiAssistantRunRouteImport } from './routes/api/public/ai-assistant/run'
import { Route as ApiPublicAdminBackfillMemoriesRouteImport } from './routes/api/public/admin/backfill-memories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSendOfferRoute = AppSendOfferRouteImport.update({
  id: '/send-offer',
  path: '/send-offer',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimeTraceRoute = AppRuntimeTraceRouteImport.update({
  id: '/runtime-trace',
  path: '/runtime-trace',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerAlertsRoute = AppManagerAlertsRouteImport.update({
  id: '/manager-alerts',
  path: '/manager-alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeCampaignRoute = AppIntakeCampaignRouteImport.update({
  id: '/intake-campaign',
  path: '/intake-campaign',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppImportLeadsRoute = AppImportLeadsRouteImport.update({
  id: '/import-leads',
  path: '/import-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoffRoute = AppHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const ApiIntrospectUiGapsRoute = ApiIntrospectUiGapsRouteImport.update({
  id: '/api/introspect/ui-gaps',
  path: '/api/introspect/ui-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntrospectTamarRoutingRoute =
  ApiIntrospectTamarRoutingRouteImport.update({
    id: '/api/introspect/tamar-routing',
    path: '/api/introspect/tamar-routing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectTamarConfigRoute =
  ApiIntrospectTamarConfigRouteImport.update({
    id: '/api/introspect/tamar-config',
    path: '/api/introspect/tamar-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectSystemOverviewRoute =
  ApiIntrospectSystemOverviewRouteImport.update({
    id: '/api/introspect/system-overview',
    path: '/api/introspect/system-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectSchemaSummaryRoute =
  ApiIntrospectSchemaSummaryRouteImport.update({
    id: '/api/introspect/schema-summary',
    path: '/api/introspect/schema-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectRecentEventsRoute =
  ApiIntrospectRecentEventsRouteImport.update({
    id: '/api/introspect/recent-events',
    path: '/api/introspect/recent-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectIntegrationsStatusRoute =
  ApiIntrospectIntegrationsStatusRouteImport.update({
    id: '/api/introspect/integrations-status',
    path: '/api/introspect/integrations-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectHealthReportRoute =
  ApiIntrospectHealthReportRouteImport.update({
    id: '/api/introspect/health-report',
    path: '/api/introspect/health-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectFrontendMapRoute =
  ApiIntrospectFrontendMapRouteImport.update({
    id: '/api/introspect/frontend-map',
    path: '/api/introspect/frontend-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectFeatureFlagsRoute =
  ApiIntrospectFeatureFlagsRouteImport.update({
    id: '/api/introspect/feature-flags',
    path: '/api/introspect/feature-flags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectDeploymentSummaryRoute =
  ApiIntrospectDeploymentSummaryRouteImport.update({
    id: '/api/introspect/deployment-summary',
    path: '/api/introspect/deployment-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectCrmSummaryRoute = ApiIntrospectCrmSummaryRouteImport.update({
  id: '/api/introspect/crm-summary',
  path: '/api/introspect/crm-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntrospectCampaignsSummaryRoute =
  ApiIntrospectCampaignsSummaryRouteImport.update({
    id: '/api/introspect/campaigns-summary',
    path: '/api/introspect/campaigns-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntrospectBackendMapRoute = ApiIntrospectBackendMapRouteImport.update({
  id: '/api/introspect/backend-map',
  path: '/api/introspect/backend-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntrospectAgentsSummaryRoute =
  ApiIntrospectAgentsSummaryRouteImport.update({
    id: '/api/introspect/agents-summary',
    path: '/api/introspect/agents-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugTamarConfigRoute = ApiDebugTamarConfigRouteImport.update({
  id: '/api/debug/tamar-config',
  path: '/api/debug/tamar-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSystemSummaryRoute = ApiDebugSystemSummaryRouteImport.update({
  id: '/api/debug/system-summary',
  path: '/api/debug/system-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSchemaSummaryRoute = ApiDebugSchemaSummaryRouteImport.update({
  id: '/api/debug/schema-summary',
  path: '/api/debug/schema-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRecentEventsRoute = ApiDebugRecentEventsRouteImport.update({
  id: '/api/debug/recent-events',
  path: '/api/debug/recent-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugIntegrationsStatusRoute =
  ApiDebugIntegrationsStatusRouteImport.update({
    id: '/api/debug/integrations-status',
    path: '/api/debug/integrations-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugFrontendMapRoute = ApiDebugFrontendMapRouteImport.update({
  id: '/api/debug/frontend-map',
  path: '/api/debug/frontend-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugAgentsSummaryRoute = ApiDebugAgentsSummaryRouteImport.update({
  id: '/api/debug/agents-summary',
  path: '/api/debug/agents-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsTamarBlocksRoute = AppSettingsTamarBlocksRouteImport.update({
  id: '/settings/tamar-blocks',
  path: '/settings/tamar-blocks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTamarRoute = AppSettingsTamarRouteImport.update({
  id: '/settings/tamar',
  path: '/settings/tamar',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsApiRoute = AppSettingsApiRouteImport.update({
  id: '/settings/api',
  path: '/settings/api',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIdRoute = AppOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOffersRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const ApiPublicWebhookTamarStatusRoute =
  ApiPublicWebhookTamarStatusRouteImport.update({
    id: '/api/public/webhook/tamar-status',
    path: '/api/public/webhook/tamar-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookTamarRoute = ApiPublicWebhookTamarRouteImport.update({
  id: '/api/public/webhook/tamar',
  path: '/api/public/webhook/tamar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRuntimeWritebackRoute =
  ApiPublicRuntimeWritebackRouteImport.update({
    id: '/api/public/runtime/writeback',
    path: '/api/public/runtime/writeback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeTamarWritebackRoute =
  ApiPublicRuntimeTamarWritebackRouteImport.update({
    id: '/api/public/runtime/tamar-writeback',
    path: '/api/public/runtime/tamar-writeback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeTamarTurnRoute =
  ApiPublicRuntimeTamarTurnRouteImport.update({
    id: '/api/public/runtime/tamar-turn',
    path: '/api/public/runtime/tamar-turn',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeTamarPackRoute =
  ApiPublicRuntimeTamarPackRouteImport.update({
    id: '/api/public/runtime/tamar-pack',
    path: '/api/public/runtime/tamar-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeLeadContextRoute =
  ApiPublicRuntimeLeadContextRouteImport.update({
    id: '/api/public/runtime/lead-context',
    path: '/api/public/runtime/lead-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeHandoffRoute = ApiPublicRuntimeHandoffRouteImport.update({
  id: '/api/public/runtime/handoff',
  path: '/api/public/runtime/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntelligenceExtractRoute =
  ApiPublicIntelligenceExtractRouteImport.update({
    id: '/api/public/intelligence/extract',
    path: '/api/public/intelligence/extract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRetryHandoffsRoute =
  ApiPublicCronRetryHandoffsRouteImport.update({
    id: '/api/public/cron/retry-handoffs',
    path: '/api/public/cron/retry-handoffs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiAssistantRunRoute = ApiPublicAiAssistantRunRouteImport.update({
  id: '/api/public/ai-assistant/run',
  path: '/api/public/ai-assistant/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminBackfillMemoriesRoute =
  ApiPublicAdminBackfillMemoriesRouteImport.update({
    id: '/api/public/admin/backfill-memories',
    path: '/api/public/admin/backfill-memories',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/handoff': typeof AppHandoffRoute
  '/import-leads': typeof AppImportLeadsRoute
  '/inbox': typeof AppInboxRoute
  '/intake-campaign': typeof AppIntakeCampaignRoute
  '/manager-alerts': typeof AppManagerAlertsRoute
  '/offers': typeof AppOffersRouteWithChildren
  '/runtime-trace': typeof AppRuntimeTraceRoute
  '/send-offer': typeof AppSendOfferRoute
  '/tasks': typeof AppTasksRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/settings/tamar': typeof AppSettingsTamarRoute
  '/settings/tamar-blocks': typeof AppSettingsTamarBlocksRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/deployment-summary': typeof ApiIntrospectDeploymentSummaryRoute
  '/api/introspect/feature-flags': typeof ApiIntrospectFeatureFlagsRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/health-report': typeof ApiIntrospectHealthReportRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/recent-events': typeof ApiIntrospectRecentEventsRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/introspect/ui-gaps': typeof ApiIntrospectUiGapsRoute
  '/api/public/admin/backfill-memories': typeof ApiPublicAdminBackfillMemoriesRoute
  '/api/public/ai-assistant/run': typeof ApiPublicAiAssistantRunRoute
  '/api/public/cron/retry-handoffs': typeof ApiPublicCronRetryHandoffsRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/runtime/handoff': typeof ApiPublicRuntimeHandoffRoute
  '/api/public/runtime/lead-context': typeof ApiPublicRuntimeLeadContextRoute
  '/api/public/runtime/tamar-pack': typeof ApiPublicRuntimeTamarPackRoute
  '/api/public/runtime/tamar-turn': typeof ApiPublicRuntimeTamarTurnRoute
  '/api/public/runtime/tamar-writeback': typeof ApiPublicRuntimeTamarWritebackRoute
  '/api/public/runtime/writeback': typeof ApiPublicRuntimeWritebackRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/handoff': typeof AppHandoffRoute
  '/import-leads': typeof AppImportLeadsRoute
  '/inbox': typeof AppInboxRoute
  '/intake-campaign': typeof AppIntakeCampaignRoute
  '/manager-alerts': typeof AppManagerAlertsRoute
  '/offers': typeof AppOffersRouteWithChildren
  '/runtime-trace': typeof AppRuntimeTraceRoute
  '/send-offer': typeof AppSendOfferRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/settings/tamar': typeof AppSettingsTamarRoute
  '/settings/tamar-blocks': typeof AppSettingsTamarBlocksRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/deployment-summary': typeof ApiIntrospectDeploymentSummaryRoute
  '/api/introspect/feature-flags': typeof ApiIntrospectFeatureFlagsRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/health-report': typeof ApiIntrospectHealthReportRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/recent-events': typeof ApiIntrospectRecentEventsRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/introspect/ui-gaps': typeof ApiIntrospectUiGapsRoute
  '/api/public/admin/backfill-memories': typeof ApiPublicAdminBackfillMemoriesRoute
  '/api/public/ai-assistant/run': typeof ApiPublicAiAssistantRunRoute
  '/api/public/cron/retry-handoffs': typeof ApiPublicCronRetryHandoffsRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/runtime/handoff': typeof ApiPublicRuntimeHandoffRoute
  '/api/public/runtime/lead-context': typeof ApiPublicRuntimeLeadContextRoute
  '/api/public/runtime/tamar-pack': typeof ApiPublicRuntimeTamarPackRoute
  '/api/public/runtime/tamar-turn': typeof ApiPublicRuntimeTamarTurnRoute
  '/api/public/runtime/tamar-writeback': typeof ApiPublicRuntimeTamarWritebackRoute
  '/api/public/runtime/writeback': typeof ApiPublicRuntimeWritebackRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/handoff': typeof AppHandoffRoute
  '/_app/import-leads': typeof AppImportLeadsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/intake-campaign': typeof AppIntakeCampaignRoute
  '/_app/manager-alerts': typeof AppManagerAlertsRoute
  '/_app/offers': typeof AppOffersRouteWithChildren
  '/_app/runtime-trace': typeof AppRuntimeTraceRoute
  '/_app/send-offer': typeof AppSendOfferRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/offers/$id': typeof AppOffersIdRoute
  '/_app/settings/api': typeof AppSettingsApiRoute
  '/_app/settings/tamar': typeof AppSettingsTamarRoute
  '/_app/settings/tamar-blocks': typeof AppSettingsTamarBlocksRoute
  '/api/debug/agents-summary': typeof ApiDebugAgentsSummaryRoute
  '/api/debug/frontend-map': typeof ApiDebugFrontendMapRoute
  '/api/debug/integrations-status': typeof ApiDebugIntegrationsStatusRoute
  '/api/debug/recent-events': typeof ApiDebugRecentEventsRoute
  '/api/debug/schema-summary': typeof ApiDebugSchemaSummaryRoute
  '/api/debug/system-summary': typeof ApiDebugSystemSummaryRoute
  '/api/debug/tamar-config': typeof ApiDebugTamarConfigRoute
  '/api/introspect/agents-summary': typeof ApiIntrospectAgentsSummaryRoute
  '/api/introspect/backend-map': typeof ApiIntrospectBackendMapRoute
  '/api/introspect/campaigns-summary': typeof ApiIntrospectCampaignsSummaryRoute
  '/api/introspect/crm-summary': typeof ApiIntrospectCrmSummaryRoute
  '/api/introspect/deployment-summary': typeof ApiIntrospectDeploymentSummaryRoute
  '/api/introspect/feature-flags': typeof ApiIntrospectFeatureFlagsRoute
  '/api/introspect/frontend-map': typeof ApiIntrospectFrontendMapRoute
  '/api/introspect/health-report': typeof ApiIntrospectHealthReportRoute
  '/api/introspect/integrations-status': typeof ApiIntrospectIntegrationsStatusRoute
  '/api/introspect/recent-events': typeof ApiIntrospectRecentEventsRoute
  '/api/introspect/schema-summary': typeof ApiIntrospectSchemaSummaryRoute
  '/api/introspect/system-overview': typeof ApiIntrospectSystemOverviewRoute
  '/api/introspect/tamar-config': typeof ApiIntrospectTamarConfigRoute
  '/api/introspect/tamar-routing': typeof ApiIntrospectTamarRoutingRoute
  '/api/introspect/ui-gaps': typeof ApiIntrospectUiGapsRoute
  '/api/public/admin/backfill-memories': typeof ApiPublicAdminBackfillMemoriesRoute
  '/api/public/ai-assistant/run': typeof ApiPublicAiAssistantRunRoute
  '/api/public/cron/retry-handoffs': typeof ApiPublicCronRetryHandoffsRoute
  '/api/public/intelligence/extract': typeof ApiPublicIntelligenceExtractRoute
  '/api/public/runtime/handoff': typeof ApiPublicRuntimeHandoffRoute
  '/api/public/runtime/lead-context': typeof ApiPublicRuntimeLeadContextRoute
  '/api/public/runtime/tamar-pack': typeof ApiPublicRuntimeTamarPackRoute
  '/api/public/runtime/tamar-turn': typeof ApiPublicRuntimeTamarTurnRoute
  '/api/public/runtime/tamar-writeback': typeof ApiPublicRuntimeTamarWritebackRoute
  '/api/public/runtime/writeback': typeof ApiPublicRuntimeWritebackRoute
  '/api/public/webhook/tamar': typeof ApiPublicWebhookTamarRoute
  '/api/public/webhook/tamar-status': typeof ApiPublicWebhookTamarStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-assistant'
    | '/campaigns'
    | '/contacts'
    | '/handoff'
    | '/import-leads'
    | '/inbox'
    | '/intake-campaign'
    | '/manager-alerts'
    | '/offers'
    | '/runtime-trace'
    | '/send-offer'
    | '/tasks'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/contacts/$id'
    | '/offers/$id'
    | '/settings/api'
    | '/settings/tamar'
    | '/settings/tamar-blocks'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/deployment-summary'
    | '/api/introspect/feature-flags'
    | '/api/introspect/frontend-map'
    | '/api/introspect/health-report'
    | '/api/introspect/integrations-status'
    | '/api/introspect/recent-events'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/introspect/ui-gaps'
    | '/api/public/admin/backfill-memories'
    | '/api/public/ai-assistant/run'
    | '/api/public/cron/retry-handoffs'
    | '/api/public/intelligence/extract'
    | '/api/public/runtime/handoff'
    | '/api/public/runtime/lead-context'
    | '/api/public/runtime/tamar-pack'
    | '/api/public/runtime/tamar-turn'
    | '/api/public/runtime/tamar-writeback'
    | '/api/public/runtime/writeback'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai-assistant'
    | '/campaigns'
    | '/contacts'
    | '/handoff'
    | '/import-leads'
    | '/inbox'
    | '/intake-campaign'
    | '/manager-alerts'
    | '/offers'
    | '/runtime-trace'
    | '/send-offer'
    | '/tasks'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/contacts/$id'
    | '/offers/$id'
    | '/settings/api'
    | '/settings/tamar'
    | '/settings/tamar-blocks'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/deployment-summary'
    | '/api/introspect/feature-flags'
    | '/api/introspect/frontend-map'
    | '/api/introspect/health-report'
    | '/api/introspect/integrations-status'
    | '/api/introspect/recent-events'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/introspect/ui-gaps'
    | '/api/public/admin/backfill-memories'
    | '/api/public/ai-assistant/run'
    | '/api/public/cron/retry-handoffs'
    | '/api/public/intelligence/extract'
    | '/api/public/runtime/handoff'
    | '/api/public/runtime/lead-context'
    | '/api/public/runtime/tamar-pack'
    | '/api/public/runtime/tamar-turn'
    | '/api/public/runtime/tamar-writeback'
    | '/api/public/runtime/writeback'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ai-assistant'
    | '/_app/campaigns'
    | '/_app/contacts'
    | '/_app/handoff'
    | '/_app/import-leads'
    | '/_app/inbox'
    | '/_app/intake-campaign'
    | '/_app/manager-alerts'
    | '/_app/offers'
    | '/_app/runtime-trace'
    | '/_app/send-offer'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/campaigns/$id'
    | '/_app/campaigns/new'
    | '/_app/contacts/$id'
    | '/_app/offers/$id'
    | '/_app/settings/api'
    | '/_app/settings/tamar'
    | '/_app/settings/tamar-blocks'
    | '/api/debug/agents-summary'
    | '/api/debug/frontend-map'
    | '/api/debug/integrations-status'
    | '/api/debug/recent-events'
    | '/api/debug/schema-summary'
    | '/api/debug/system-summary'
    | '/api/debug/tamar-config'
    | '/api/introspect/agents-summary'
    | '/api/introspect/backend-map'
    | '/api/introspect/campaigns-summary'
    | '/api/introspect/crm-summary'
    | '/api/introspect/deployment-summary'
    | '/api/introspect/feature-flags'
    | '/api/introspect/frontend-map'
    | '/api/introspect/health-report'
    | '/api/introspect/integrations-status'
    | '/api/introspect/recent-events'
    | '/api/introspect/schema-summary'
    | '/api/introspect/system-overview'
    | '/api/introspect/tamar-config'
    | '/api/introspect/tamar-routing'
    | '/api/introspect/ui-gaps'
    | '/api/public/admin/backfill-memories'
    | '/api/public/ai-assistant/run'
    | '/api/public/cron/retry-handoffs'
    | '/api/public/intelligence/extract'
    | '/api/public/runtime/handoff'
    | '/api/public/runtime/lead-context'
    | '/api/public/runtime/tamar-pack'
    | '/api/public/runtime/tamar-turn'
    | '/api/public/runtime/tamar-writeback'
    | '/api/public/runtime/writeback'
    | '/api/public/webhook/tamar'
    | '/api/public/webhook/tamar-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDebugAgentsSummaryRoute: typeof ApiDebugAgentsSummaryRoute
  ApiDebugFrontendMapRoute: typeof ApiDebugFrontendMapRoute
  ApiDebugIntegrationsStatusRoute: typeof ApiDebugIntegrationsStatusRoute
  ApiDebugRecentEventsRoute: typeof ApiDebugRecentEventsRoute
  ApiDebugSchemaSummaryRoute: typeof ApiDebugSchemaSummaryRoute
  ApiDebugSystemSummaryRoute: typeof ApiDebugSystemSummaryRoute
  ApiDebugTamarConfigRoute: typeof ApiDebugTamarConfigRoute
  ApiIntrospectAgentsSummaryRoute: typeof ApiIntrospectAgentsSummaryRoute
  ApiIntrospectBackendMapRoute: typeof ApiIntrospectBackendMapRoute
  ApiIntrospectCampaignsSummaryRoute: typeof ApiIntrospectCampaignsSummaryRoute
  ApiIntrospectCrmSummaryRoute: typeof ApiIntrospectCrmSummaryRoute
  ApiIntrospectDeploymentSummaryRoute: typeof ApiIntrospectDeploymentSummaryRoute
  ApiIntrospectFeatureFlagsRoute: typeof ApiIntrospectFeatureFlagsRoute
  ApiIntrospectFrontendMapRoute: typeof ApiIntrospectFrontendMapRoute
  ApiIntrospectHealthReportRoute: typeof ApiIntrospectHealthReportRoute
  ApiIntrospectIntegrationsStatusRoute: typeof ApiIntrospectIntegrationsStatusRoute
  ApiIntrospectRecentEventsRoute: typeof ApiIntrospectRecentEventsRoute
  ApiIntrospectSchemaSummaryRoute: typeof ApiIntrospectSchemaSummaryRoute
  ApiIntrospectSystemOverviewRoute: typeof ApiIntrospectSystemOverviewRoute
  ApiIntrospectTamarConfigRoute: typeof ApiIntrospectTamarConfigRoute
  ApiIntrospectTamarRoutingRoute: typeof ApiIntrospectTamarRoutingRoute
  ApiIntrospectUiGapsRoute: typeof ApiIntrospectUiGapsRoute
  ApiPublicAdminBackfillMemoriesRoute: typeof ApiPublicAdminBackfillMemoriesRoute
  ApiPublicAiAssistantRunRoute: typeof ApiPublicAiAssistantRunRoute
  ApiPublicCronRetryHandoffsRoute: typeof ApiPublicCronRetryHandoffsRoute
  ApiPublicIntelligenceExtractRoute: typeof ApiPublicIntelligenceExtractRoute
  ApiPublicRuntimeHandoffRoute: typeof ApiPublicRuntimeHandoffRoute
  ApiPublicRuntimeLeadContextRoute: typeof ApiPublicRuntimeLeadContextRoute
  ApiPublicRuntimeTamarPackRoute: typeof ApiPublicRuntimeTamarPackRoute
  ApiPublicRuntimeTamarTurnRoute: typeof ApiPublicRuntimeTamarTurnRoute
  ApiPublicRuntimeTamarWritebackRoute: typeof ApiPublicRuntimeTamarWritebackRoute
  ApiPublicRuntimeWritebackRoute: typeof ApiPublicRuntimeWritebackRoute
  ApiPublicWebhookTamarRoute: typeof ApiPublicWebhookTamarRoute
  ApiPublicWebhookTamarStatusRoute: typeof ApiPublicWebhookTamarStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send-offer': {
      id: '/_app/send-offer'
      path: '/send-offer'
      fullPath: '/send-offer'
      preLoaderRoute: typeof AppSendOfferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtime-trace': {
      id: '/_app/runtime-trace'
      path: '/runtime-trace'
      fullPath: '/runtime-trace'
      preLoaderRoute: typeof AppRuntimeTraceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager-alerts': {
      id: '/_app/manager-alerts'
      path: '/manager-alerts'
      fullPath: '/manager-alerts'
      preLoaderRoute: typeof AppManagerAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake-campaign': {
      id: '/_app/intake-campaign'
      path: '/intake-campaign'
      fullPath: '/intake-campaign'
      preLoaderRoute: typeof AppIntakeCampaignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-leads': {
      id: '/_app/import-leads'
      path: '/import-leads'
      fullPath: '/import-leads'
      preLoaderRoute: typeof AppImportLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handoff': {
      id: '/_app/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof AppHandoffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/introspect/ui-gaps': {
      id: '/api/introspect/ui-gaps'
      path: '/api/introspect/ui-gaps'
      fullPath: '/api/introspect/ui-gaps'
      preLoaderRoute: typeof ApiIntrospectUiGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/tamar-routing': {
      id: '/api/introspect/tamar-routing'
      path: '/api/introspect/tamar-routing'
      fullPath: '/api/introspect/tamar-routing'
      preLoaderRoute: typeof ApiIntrospectTamarRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/tamar-config': {
      id: '/api/introspect/tamar-config'
      path: '/api/introspect/tamar-config'
      fullPath: '/api/introspect/tamar-config'
      preLoaderRoute: typeof ApiIntrospectTamarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/system-overview': {
      id: '/api/introspect/system-overview'
      path: '/api/introspect/system-overview'
      fullPath: '/api/introspect/system-overview'
      preLoaderRoute: typeof ApiIntrospectSystemOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/schema-summary': {
      id: '/api/introspect/schema-summary'
      path: '/api/introspect/schema-summary'
      fullPath: '/api/introspect/schema-summary'
      preLoaderRoute: typeof ApiIntrospectSchemaSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/recent-events': {
      id: '/api/introspect/recent-events'
      path: '/api/introspect/recent-events'
      fullPath: '/api/introspect/recent-events'
      preLoaderRoute: typeof ApiIntrospectRecentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/integrations-status': {
      id: '/api/introspect/integrations-status'
      path: '/api/introspect/integrations-status'
      fullPath: '/api/introspect/integrations-status'
      preLoaderRoute: typeof ApiIntrospectIntegrationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/health-report': {
      id: '/api/introspect/health-report'
      path: '/api/introspect/health-report'
      fullPath: '/api/introspect/health-report'
      preLoaderRoute: typeof ApiIntrospectHealthReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/frontend-map': {
      id: '/api/introspect/frontend-map'
      path: '/api/introspect/frontend-map'
      fullPath: '/api/introspect/frontend-map'
      preLoaderRoute: typeof ApiIntrospectFrontendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/feature-flags': {
      id: '/api/introspect/feature-flags'
      path: '/api/introspect/feature-flags'
      fullPath: '/api/introspect/feature-flags'
      preLoaderRoute: typeof ApiIntrospectFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/deployment-summary': {
      id: '/api/introspect/deployment-summary'
      path: '/api/introspect/deployment-summary'
      fullPath: '/api/introspect/deployment-summary'
      preLoaderRoute: typeof ApiIntrospectDeploymentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/crm-summary': {
      id: '/api/introspect/crm-summary'
      path: '/api/introspect/crm-summary'
      fullPath: '/api/introspect/crm-summary'
      preLoaderRoute: typeof ApiIntrospectCrmSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/campaigns-summary': {
      id: '/api/introspect/campaigns-summary'
      path: '/api/introspect/campaigns-summary'
      fullPath: '/api/introspect/campaigns-summary'
      preLoaderRoute: typeof ApiIntrospectCampaignsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/backend-map': {
      id: '/api/introspect/backend-map'
      path: '/api/introspect/backend-map'
      fullPath: '/api/introspect/backend-map'
      preLoaderRoute: typeof ApiIntrospectBackendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introspect/agents-summary': {
      id: '/api/introspect/agents-summary'
      path: '/api/introspect/agents-summary'
      fullPath: '/api/introspect/agents-summary'
      preLoaderRoute: typeof ApiIntrospectAgentsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/tamar-config': {
      id: '/api/debug/tamar-config'
      path: '/api/debug/tamar-config'
      fullPath: '/api/debug/tamar-config'
      preLoaderRoute: typeof ApiDebugTamarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/system-summary': {
      id: '/api/debug/system-summary'
      path: '/api/debug/system-summary'
      fullPath: '/api/debug/system-summary'
      preLoaderRoute: typeof ApiDebugSystemSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/schema-summary': {
      id: '/api/debug/schema-summary'
      path: '/api/debug/schema-summary'
      fullPath: '/api/debug/schema-summary'
      preLoaderRoute: typeof ApiDebugSchemaSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/recent-events': {
      id: '/api/debug/recent-events'
      path: '/api/debug/recent-events'
      fullPath: '/api/debug/recent-events'
      preLoaderRoute: typeof ApiDebugRecentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/integrations-status': {
      id: '/api/debug/integrations-status'
      path: '/api/debug/integrations-status'
      fullPath: '/api/debug/integrations-status'
      preLoaderRoute: typeof ApiDebugIntegrationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/frontend-map': {
      id: '/api/debug/frontend-map'
      path: '/api/debug/frontend-map'
      fullPath: '/api/debug/frontend-map'
      preLoaderRoute: typeof ApiDebugFrontendMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/agents-summary': {
      id: '/api/debug/agents-summary'
      path: '/api/debug/agents-summary'
      fullPath: '/api/debug/agents-summary'
      preLoaderRoute: typeof ApiDebugAgentsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/tamar-blocks': {
      id: '/_app/settings/tamar-blocks'
      path: '/settings/tamar-blocks'
      fullPath: '/settings/tamar-blocks'
      preLoaderRoute: typeof AppSettingsTamarBlocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tamar': {
      id: '/_app/settings/tamar'
      path: '/settings/tamar'
      fullPath: '/settings/tamar'
      preLoaderRoute: typeof AppSettingsTamarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/api': {
      id: '/_app/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AppSettingsApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers/$id': {
      id: '/_app/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AppOffersIdRouteImport
      parentRoute: typeof AppOffersRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/api/public/webhook/tamar-status': {
      id: '/api/public/webhook/tamar-status'
      path: '/api/public/webhook/tamar-status'
      fullPath: '/api/public/webhook/tamar-status'
      preLoaderRoute: typeof ApiPublicWebhookTamarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/tamar': {
      id: '/api/public/webhook/tamar'
      path: '/api/public/webhook/tamar'
      fullPath: '/api/public/webhook/tamar'
      preLoaderRoute: typeof ApiPublicWebhookTamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/writeback': {
      id: '/api/public/runtime/writeback'
      path: '/api/public/runtime/writeback'
      fullPath: '/api/public/runtime/writeback'
      preLoaderRoute: typeof ApiPublicRuntimeWritebackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/tamar-writeback': {
      id: '/api/public/runtime/tamar-writeback'
      path: '/api/public/runtime/tamar-writeback'
      fullPath: '/api/public/runtime/tamar-writeback'
      preLoaderRoute: typeof ApiPublicRuntimeTamarWritebackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/tamar-turn': {
      id: '/api/public/runtime/tamar-turn'
      path: '/api/public/runtime/tamar-turn'
      fullPath: '/api/public/runtime/tamar-turn'
      preLoaderRoute: typeof ApiPublicRuntimeTamarTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/tamar-pack': {
      id: '/api/public/runtime/tamar-pack'
      path: '/api/public/runtime/tamar-pack'
      fullPath: '/api/public/runtime/tamar-pack'
      preLoaderRoute: typeof ApiPublicRuntimeTamarPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/lead-context': {
      id: '/api/public/runtime/lead-context'
      path: '/api/public/runtime/lead-context'
      fullPath: '/api/public/runtime/lead-context'
      preLoaderRoute: typeof ApiPublicRuntimeLeadContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime/handoff': {
      id: '/api/public/runtime/handoff'
      path: '/api/public/runtime/handoff'
      fullPath: '/api/public/runtime/handoff'
      preLoaderRoute: typeof ApiPublicRuntimeHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intelligence/extract': {
      id: '/api/public/intelligence/extract'
      path: '/api/public/intelligence/extract'
      fullPath: '/api/public/intelligence/extract'
      preLoaderRoute: typeof ApiPublicIntelligenceExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/retry-handoffs': {
      id: '/api/public/cron/retry-handoffs'
      path: '/api/public/cron/retry-handoffs'
      fullPath: '/api/public/cron/retry-handoffs'
      preLoaderRoute: typeof ApiPublicCronRetryHandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-assistant/run': {
      id: '/api/public/ai-assistant/run'
      path: '/api/public/ai-assistant/run'
      fullPath: '/api/public/ai-assistant/run'
      preLoaderRoute: typeof ApiPublicAiAssistantRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/backfill-memories': {
      id: '/api/public/admin/backfill-memories'
      path: '/api/public/admin/backfill-memories'
      fullPath: '/api/public/admin/backfill-memories'
      preLoaderRoute: typeof ApiPublicAdminBackfillMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppOffersRouteChildren {
  AppOffersIdRoute: typeof AppOffersIdRoute
}

const AppOffersRouteChildren: AppOffersRouteChildren = {
  AppOffersIdRoute: AppOffersIdRoute,
}

const AppOffersRouteWithChildren = AppOffersRoute._addFileChildren(
  AppOffersRouteChildren,
)

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppHandoffRoute: typeof AppHandoffRoute
  AppImportLeadsRoute: typeof AppImportLeadsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntakeCampaignRoute: typeof AppIntakeCampaignRoute
  AppManagerAlertsRoute: typeof AppManagerAlertsRoute
  AppOffersRoute: typeof AppOffersRouteWithChildren
  AppRuntimeTraceRoute: typeof AppRuntimeTraceRoute
  AppSendOfferRoute: typeof AppSendOfferRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsApiRoute: typeof AppSettingsApiRoute
  AppSettingsTamarRoute: typeof AppSettingsTamarRoute
  AppSettingsTamarBlocksRoute: typeof AppSettingsTamarBlocksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppHandoffRoute: AppHandoffRoute,
  AppImportLeadsRoute: AppImportLeadsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntakeCampaignRoute: AppIntakeCampaignRoute,
  AppManagerAlertsRoute: AppManagerAlertsRoute,
  AppOffersRoute: AppOffersRouteWithChildren,
  AppRuntimeTraceRoute: AppRuntimeTraceRoute,
  AppSendOfferRoute: AppSendOfferRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsApiRoute: AppSettingsApiRoute,
  AppSettingsTamarRoute: AppSettingsTamarRoute,
  AppSettingsTamarBlocksRoute: AppSettingsTamarBlocksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDebugAgentsSummaryRoute: ApiDebugAgentsSummaryRoute,
  ApiDebugFrontendMapRoute: ApiDebugFrontendMapRoute,
  ApiDebugIntegrationsStatusRoute: ApiDebugIntegrationsStatusRoute,
  ApiDebugRecentEventsRoute: ApiDebugRecentEventsRoute,
  ApiDebugSchemaSummaryRoute: ApiDebugSchemaSummaryRoute,
  ApiDebugSystemSummaryRoute: ApiDebugSystemSummaryRoute,
  ApiDebugTamarConfigRoute: ApiDebugTamarConfigRoute,
  ApiIntrospectAgentsSummaryRoute: ApiIntrospectAgentsSummaryRoute,
  ApiIntrospectBackendMapRoute: ApiIntrospectBackendMapRoute,
  ApiIntrospectCampaignsSummaryRoute: ApiIntrospectCampaignsSummaryRoute,
  ApiIntrospectCrmSummaryRoute: ApiIntrospectCrmSummaryRoute,
  ApiIntrospectDeploymentSummaryRoute: ApiIntrospectDeploymentSummaryRoute,
  ApiIntrospectFeatureFlagsRoute: ApiIntrospectFeatureFlagsRoute,
  ApiIntrospectFrontendMapRoute: ApiIntrospectFrontendMapRoute,
  ApiIntrospectHealthReportRoute: ApiIntrospectHealthReportRoute,
  ApiIntrospectIntegrationsStatusRoute: ApiIntrospectIntegrationsStatusRoute,
  ApiIntrospectRecentEventsRoute: ApiIntrospectRecentEventsRoute,
  ApiIntrospectSchemaSummaryRoute: ApiIntrospectSchemaSummaryRoute,
  ApiIntrospectSystemOverviewRoute: ApiIntrospectSystemOverviewRoute,
  ApiIntrospectTamarConfigRoute: ApiIntrospectTamarConfigRoute,
  ApiIntrospectTamarRoutingRoute: ApiIntrospectTamarRoutingRoute,
  ApiIntrospectUiGapsRoute: ApiIntrospectUiGapsRoute,
  ApiPublicAdminBackfillMemoriesRoute: ApiPublicAdminBackfillMemoriesRoute,
  ApiPublicAiAssistantRunRoute: ApiPublicAiAssistantRunRoute,
  ApiPublicCronRetryHandoffsRoute: ApiPublicCronRetryHandoffsRoute,
  ApiPublicIntelligenceExtractRoute: ApiPublicIntelligenceExtractRoute,
  ApiPublicRuntimeHandoffRoute: ApiPublicRuntimeHandoffRoute,
  ApiPublicRuntimeLeadContextRoute: ApiPublicRuntimeLeadContextRoute,
  ApiPublicRuntimeTamarPackRoute: ApiPublicRuntimeTamarPackRoute,
  ApiPublicRuntimeTamarTurnRoute: ApiPublicRuntimeTamarTurnRoute,
  ApiPublicRuntimeTamarWritebackRoute: ApiPublicRuntimeTamarWritebackRoute,
  ApiPublicRuntimeWritebackRoute: ApiPublicRuntimeWritebackRoute,
  ApiPublicWebhookTamarRoute: ApiPublicWebhookTamarRoute,
  ApiPublicWebhookTamarStatusRoute: ApiPublicWebhookTamarStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
